### ISSUE TITLE
jdk 11 ubuntu build failed with 'Exception in thread "main" java.lang.RuntimeException: Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases29.dat - cannot continue'

### ISSUE THREAD

**Issue by sophia-guo** [eclipse-openj9/build-openj9#25]
jdk 11 ubuntu build failed with message: 'Exception in thread "main" java.lang.RuntimeException: Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases29.dat - cannot continue'  from May 12 or May 13th.

```
Generating DDR pointer and structure class files
Exception in thread "main" java.lang.RuntimeException: Failed to load alias map from resource: /com/ibm/j9ddr/StructureAliases29.dat - cannot continue
	at com.ibm.j9ddr.StructureReader.loadAliasMapData(StructureReader.java:438)
	at com.ibm.j9ddr.StructureReader.loadAliasMap(StructureReader.java:306)
	at com.ibm.j9ddr.StructureReader.applyAliases(StructureReader.java:222)
	at com.ibm.j9ddr.StructureReader.<init>(StructureReader.java:120)
	at com.ibm.j9ddr.tools.ClassGenerator.readBlob(ClassGenerator.java:93)
	at com.ibm.j9ddr.tools.ClassGenerator.run(ClassGenerator.java:174)
	at com.ibm.j9ddr.tools.ClassGenerator.main(ClassGenerator.java:79)
make[4]: *** [/home/runner/work/build-openj9/build-openj9/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/support/ddr/classes.done] Error 1
/home/runner/work/build-openj9/build-openj9/openj9-openjdk-jdk11/closed/DDR.gmk:106: recipe for target '/home/runner/work/build-openj9/build-openj9/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/support/ddr/classes.done' failed
Gensrc-openj9.dtfj.gmk:25: recipe for target 'all' failed
make[3]: *** [all] Error 2
make/Main.gmk:112: recipe for target 'openj9.dtfj-gensrc-src' failed
make[2]: *** [openj9.dtfj-gensrc-src] Error 1
```
https://github.com/eclipse-openj9/build-openj9/runs/2659808852?check_suite_focus=true

**Comment by pshipton** [comment]
@sophia-guo what boot JVM are you using? We recently discovered you need a recent jdk11 boot JVM for this to work. If you are using jdk10 pls update to jdk11. If you are using an older version of jdk11, pls update to the latest.

**Comment by sophia-guo** [comment]
Thanks @pshipton! Yes, I'm using jdk10. Will try to update to a new JDK11.
